# refer: https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_PAT }}

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    registries:
      - github-octocat
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"
      day: "sunday"
      time: "16:00"

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    registries:
      - github-octocat
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"
      day: "sunday"
      time: "16:00"
